CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME users_seq) PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME categories_seq) PRIMARY KEY,
    user_id bigint,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT user_category UNIQUE (user_id, name),
    CONSTRAINT fk_category_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME questions_seq) PRIMARY KEY,
    user_id bigint,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_question_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE questions_categories (
    question_id bigint,
    category_id bigint,
    PRIMARY KEY (question_id, category_id),
    CONSTRAINT fk_qc_question FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT fk_qc_category FOREIGN KEY (category_id) REFERENCES categories(id)
);